#!/bin/sh
if [ $1 -le 25 ]; then
	notify-send -t 5000 -i "/usr/share/icons/Adwaita/32x32/legacy/battery-caution-charging-symbolic.symbolic.png" "Low Battery ($1%)" "Plug-in immediately!"
elif [ $1 -le 10 ]; then
	notify-send -t 5000 -i -u critical "/usr/share/icons/Adwaita/32x32/legacy/battery-caution-charging-symbolic.symbolic.png" "Low Battery ($1%)" "Plug-in immediately!"
	[ $1 -le 4 ] && notify-send -t 5000 -u critical -i "System shutting down . . ."
elif [ $1 -gt 75 ]; then
	notify-send -t 5000 -i "/usr/share/icons/Adwaita/32x32/legacy/battery-caution-charging-symbolic.symbolic.png" "High Battery ($1%)" "Plug-out immediately!"
fi
