#! /bin/sh

# generate pywal colorscheme based on the current wallpaper
wal -c
wal -i $HOME/.local/share/wallpaper --backend colorz -nst
cp $HOME/.cache/wal/colors.Xresources $HOME/.local/share/xresources.d/wal-colors
[ "$1" == "-i" ] && cp $HOME/.cache/wal/colors.Xresources $HOME/.local/share/xresources.d/selected-colors
