#!/bin/sh

path="$HOME/Pictures/Wallpapers"
[ -n "$1" ] && path=$path/$1*
[ ! -d $path ] && exit 1
randombg="$(find $path -type f -name '*g' -not -path '*/.git/*' | shuf | head -1)"
setbg "$randombg" "$2" &
