#!/bin/sh

sub_dir=$1
[ -z $1 ] && sub_dir=../W

wallpaper_dir="$HOME/Pictures/Wallpapers"
[ -d $wallpaper_dir/$sub_dir* ] && src=$wallpaper_dir/$sub_dir*
randombg="$(find $src -type f -name '*g' -not -path '*/.git/*' | shuf | head -1)"
setbg "$randombg" "$2"
